tap "alexnabokikh/tfsort"
tap "cesarferreira/tap"
tap "ekristen/tap"
tap "fluxcd/tap"
tap "jwbargsten/misc"
tap "manaflow-ai/cmux"
tap "norwoodj/tap"
tap "romkatv/powerlevel10k"
tap "spacelift-io/spacelift"

brew "ansible"
brew "bat"
brew "betterleaks"
brew "buildpacks/tap/pack"
brew "cmake"
brew "duti"
brew "ekristen/tap/aws-nuke"
brew "fd"
brew "fswatch"
brew "fzf"
brew "gawk"
brew "gh"
brew "ghq"        # pinned — joey's `git` wrapper depends on it (clone→ghq)
brew "git-lfs"
brew "git-town"   # pinned — joey's `git` wrapper depends on it (hack/sync/propose)
brew "go"
brew "goreleaser"
brew "gpg"
brew "gnupg"
brew "hadolint"
brew "helm"
brew "hopenpgp-tools"
brew "hub"
brew "jq"
brew "kind"
brew "kubectx"
brew "kubecm"
brew "kustomize"
brew "lazygit"
brew "lua-language-server"
brew "markdownlint-cli2"
brew "mas"
brew "mise"
brew "neovim"
brew "languagetool"
brew "openssh"
brew "pinentry-mac"
brew "podman"
brew "protobuf"
brew "pyright"
brew "cesarferreira/tap/rip"
brew "ripgrep"
brew "ruff"
brew "selene"
brew "shellcheck"
brew "sops"
brew "spacelift-io/spacelift/spacectl"
brew "telnet"
brew "terraform-docs"
brew "tfsort"
brew "tmux"
brew "tree"
brew "typescript-language-server"
brew "wget"
brew "yadm"
brew "yamllint"
brew "yarn"
brew "ykman"
brew "ykpers"
brew "ytt"
brew "yubikey-personalization"
brew "zsh-syntax-highlighting"
brew "oh-my-posh"

brew "fluxcd/tap/flux"
brew "norwoodj/tap/helm-docs"

cask "arc"
cask "alfred"
cask "cmux"
cask "discord"
cask "docker"
cask "elgato-camera-hub"
cask "elgato-stream-deck"
cask "elgato-wave-link"
cask "firefox"
cask "font-fira-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "google-cloud-sdk"
cask "hammerspoon"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "languagetool"
cask "moom"
cask "mutedeck"
cask "obs"
cask "obsidian"
cask "session-manager-plugin"
cask "sequel-ace"
cask "sublime-text"
cask "synology-drive"
cask "chatgpt"
cask "1password/tap/1password-cli"
cask "1password"
cask "zoom"

mas "Amphetamine", id: 937984704
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "In Your Face: Meeting Reminder", id: 1476964367
mas "Next Meeting", id: 1017470484
mas "WireGuard", id: 1451685025
