tap "alexnabokikh/tfsort"
tap "cesarferreira/tap"
tap "ekristen/tap"
tap "fluxcd/tap"
tap "jwbargsten/misc"
tap "norwoodj/tap"
tap "romkatv/powerlevel10k"
tap "spacelift-io/spacelift"
tap "theoutdoorprogrammer/tap"

brew "ansible"
brew "aubio"       # beat detection for song-of-the-week hook snapping
brew "bat"
brew "betterleaks"
brew "buf"
brew "buildpacks/tap/pack"
brew "cmake"
brew "docker-buildx" # `docker build` needs it for $BUILDPLATFORM; wire it in via cliPluginsExtraDirs
brew "duti"
brew "ekristen/tap/aws-nuke"
brew "exiftool"
brew "fd"
brew "ffmpeg"      # cutting, levelling and crossfading audio
brew "fswatch"
brew "fzf"
brew "gawk"
brew "gh"
brew "ghq"        # joey's `git` wrapper depends on it (clone→ghq)
brew "git-lfs"
brew "git-town"   # joey's `git` wrapper depends on it (hack/sync/propose)
brew "go"
brew "goreleaser"
brew "gpg"
brew "gnupg"
brew "hadolint"
brew "helm"
brew "herdr"      # the terminal multiplexer Ghostty launches (home repo ADR 0004)
brew "hopenpgp-tools"
brew "hub"
brew "imagemagick" # composites the song-of-the-week credits tile
brew "jq"
brew "kind"
brew "kubectx"
brew "kubecm"
brew "kustomize"
brew "lazygit"
brew "lua-language-server"
brew "markdownlint-cli2"
brew "mas"
# mermaid-ascii has no formula in core and upstream publishes no tap, so it is
# NOT here — scripts/boot-update.sh `go install`s it (home repo ADR 0001).
brew "mise"
brew "neovim"
brew "languagetool"
brew "opa"
brew "pinentry-mac"
brew "podman"
brew "protobuf"
brew "pyright"
brew "cesarferreira/tap/rip"
brew "ripgrep"
brew "ruff"
brew "selene"
brew "shellcheck"
brew "sops"
brew "swiftlint"
brew "telnet"
brew "terraform-docs"
brew "tfsort"
brew "tmux"
brew "tree"
brew "uv"          # runs the nano-banana-pro image script's inline deps
brew "typescript-language-server"
brew "wget"
brew "yadm"
brew "yamllint"
brew "yarn"
brew "ykman"
brew "ykpers"
brew "yt-dlp"      # pulls source audio for the song-of-the-week megamix
brew "ytt"
brew "yubico-piv-tool"
brew "yubikey-personalization"
brew "zig"
brew "zsh-syntax-highlighting"
brew "oh-my-posh"

brew "fluxcd/tap/flux"
brew "norwoodj/tap/helm-docs"

cask "arc"
cask "alfred"
cask "claude-code@latest" # Claude Code CLI, `claude`
cask "codex"      # OpenAI Codex CLI, `codex`, signs in with the ChatGPT plan
cask "cursor-cli" # Cursor's terminal agent, `cursor-agent`, shares the Cursor subscription
cask "discord"
cask "docker"
cask "drawio"
cask "elgato-camera-hub"
cask "elgato-stream-deck"
cask "elgato-wave-link"
cask "firefox"
cask "fledge"
cask "font-fira-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "gcloud-cli"
cask "hammerspoon"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "languagetool"
cask "moom"
cask "mutedeck"
cask "obs"
cask "obsidian"
cask "ollie-hooks"
cask "session-manager-plugin"
cask "sequel-ace"
cask "spacelift-io/spacelift/spacectl" # a cask since 1.25, not a formula; there is no core spacectl
cask "sublime-text"
cask "synology-drive"
cask "chatgpt"
cask "1password/tap/1password-cli"
cask "1password"
cask "zoom"

mas "Amphetamine", id: 937984704
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "In Your Face: Meeting Reminder", id: 1476964367
mas "Next Meeting", id: 1017470484
mas "WireGuard", id: 1451685025
